apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-1.13
  namespace: project1
spec:
  replicas: 2
  selector:
    project: lab7
    service: web
    version: "0.2"
  template:
    metadata:
      name: nginx
      labels:
        project: lab7
        service: web
        version: "0.2"
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.1
        ports:
        - containerPort: 80
