from jenkinsci/jenkins

#Disable Inital Setup Wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

#Copy security.groovy Script

COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy

# Copy plugins.txt file
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

#Install Plugins

RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# install Maven
USER root
RUN apt-get update && apt-get install -y maven
USER jenkins
