apiVersion: v1
kind: Pod
metadata:
  name: 2c-pod
  namespace: project1
spec:
  containers:
  - name: web
    image: nginx
  - name: centos
    image: centos
    command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/;sleep 10; done"]
