apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace: project1
spec:
  replicas: 2
  selector:
    project: lab4
    service: web
    version: "0.1"
  template:
    metadata:
      name: nginx
      labels:
        project: lab4
        service: web
        version: "0.1"
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

