apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret
  namespace: project1
spec:
  containers:
  - name: envars-test-container
    image: nginx
    envFrom:
    - secretRef:
        name: test-secret
